Starting flurry as ubuntu
[2016-04-09 11:12:17 +0000] [11391] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f405590e410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f405590e140>
  pre_fork: <function pre_fork at 0x7f405590e2a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f4055983f50>
  pre_exec: <function pre_exec at 0x7f405590e9b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f405590e578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f40559130c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f405590eb18>
  post_request: <function post_request at 0x7f405590ec08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f405590e6e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f405590ed70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f4055983de8>
  worker_abort: <function worker_abort at 0x7f405590e848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f405590eed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-09 11:12:17 +0000] [11391] [INFO] Starting gunicorn 19.4.5
[2016-04-09 11:12:17 +0000] [11391] [DEBUG] Arbiter booted
[2016-04-09 11:12:17 +0000] [11391] [INFO] Listening at: http://0.0.0.0:8001 (11391)
[2016-04-09 11:12:17 +0000] [11391] [INFO] Using worker: sync
[2016-04-09 11:12:17 +0000] [11397] [INFO] Booting worker with pid: 11397
[2016-04-09 11:12:17 +0000] [11398] [INFO] Booting worker with pid: 11398
[2016-04-09 11:12:17 +0000] [11401] [INFO] Booting worker with pid: 11401
[2016-04-09 11:12:17 +0000] [11391] [DEBUG] 3 workers
[2016-04-09 11:25:30 +0000] [11398] [DEBUG] GET /
Not Found: /
[2016-04-09 11:25:35 +0000] [11401] [DEBUG] GET /admin/
[2016-04-09 11:25:35 +0000] [11397] [DEBUG] GET /admin/login/
[2016-04-09 11:25:39 +0000] [11401] [DEBUG] GET /admin/login/
[2016-04-09 11:25:47 +0000] [11397] [DEBUG] GET /api/v1/flurry/
[2016-04-09 11:27:33 +0000] [11398] [DEBUG] GET /api/v1/flurry/
[2016-04-09 11:28:45 +0000] [11401] [DEBUG] GET /
Not Found: /
[2016-04-09 11:34:49 +0000] [11391] [INFO] Handling signal: term
[2016-04-09 11:34:49 +0000] [11401] [INFO] Worker exiting (pid: 11401)
[2016-04-09 11:34:49 +0000] [11397] [INFO] Worker exiting (pid: 11397)
[2016-04-09 11:34:49 +0000] [11398] [INFO] Worker exiting (pid: 11398)
[2016-04-09 11:34:49 +0000] [11391] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-09 11:34:50 +0000] [12412] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7fa5f0be8410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7fa5f0be8140>
  pre_fork: <function pre_fork at 0x7fa5f0be82a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7fa5f0c5df50>
  pre_exec: <function pre_exec at 0x7fa5f0be89b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7fa5f0be8578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7fa5f0bed0c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7fa5f0be8b18>
  post_request: <function post_request at 0x7fa5f0be8c08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7fa5f0be86e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7fa5f0be8d70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7fa5f0c5dde8>
  worker_abort: <function worker_abort at 0x7fa5f0be8848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7fa5f0be8ed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-09 11:34:50 +0000] [12412] [INFO] Starting gunicorn 19.4.5
[2016-04-09 11:34:50 +0000] [12412] [DEBUG] Arbiter booted
[2016-04-09 11:34:50 +0000] [12412] [INFO] Listening at: http://0.0.0.0:8001 (12412)
[2016-04-09 11:34:50 +0000] [12412] [INFO] Using worker: sync
[2016-04-09 11:34:50 +0000] [12418] [INFO] Booting worker with pid: 12418
[2016-04-09 11:34:50 +0000] [12421] [INFO] Booting worker with pid: 12421
[2016-04-09 11:34:50 +0000] [12424] [INFO] Booting worker with pid: 12424
[2016-04-09 11:34:50 +0000] [12412] [DEBUG] 3 workers
[2016-04-09 11:34:59 +0000] [12421] [DEBUG] GET /
/home/ubuntu/flurry/flurry/urls.py:23: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got django.views.generic.simple.direct_to_template). Pass the callable instead.
  url(r'^$', 'django.views.generic.simple.direct_to_template', {'template': 'homepage.html'}, name='index'),

Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 134, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 376, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 248, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 255, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 124, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import 'django.views.generic.simple.direct_to_template'. Parent module django.views.generic.simple does not exist.
[2016-04-09 11:37:42 +0000] [12412] [INFO] Handling signal: term
[2016-04-09 11:37:42 +0000] [12424] [INFO] Worker exiting (pid: 12424)
[2016-04-09 11:37:42 +0000] [12418] [INFO] Worker exiting (pid: 12418)
[2016-04-09 11:37:42 +0000] [12421] [INFO] Worker exiting (pid: 12421)
[2016-04-09 11:37:42 +0000] [12412] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-09 11:37:43 +0000] [12441] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f647f371410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f647f371140>
  pre_fork: <function pre_fork at 0x7f647f3712a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f647f3e6f50>
  pre_exec: <function pre_exec at 0x7f647f3719b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f647f371578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f647f3760c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f647f371b18>
  post_request: <function post_request at 0x7f647f371c08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f647f3716e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f647f371d70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f647f3e6de8>
  worker_abort: <function worker_abort at 0x7f647f371848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f647f371ed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-09 11:37:43 +0000] [12441] [INFO] Starting gunicorn 19.4.5
[2016-04-09 11:37:43 +0000] [12441] [DEBUG] Arbiter booted
[2016-04-09 11:37:43 +0000] [12441] [INFO] Listening at: http://0.0.0.0:8001 (12441)
[2016-04-09 11:37:43 +0000] [12441] [INFO] Using worker: sync
[2016-04-09 11:37:43 +0000] [12447] [INFO] Booting worker with pid: 12447
[2016-04-09 11:37:43 +0000] [12450] [INFO] Booting worker with pid: 12450
[2016-04-09 11:37:43 +0000] [12451] [INFO] Booting worker with pid: 12451
[2016-04-09 11:37:43 +0000] [12441] [DEBUG] 3 workers
[2016-04-09 11:37:47 +0000] [12450] [DEBUG] GET /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 74, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: static/homepage.html
[2016-04-09 11:37:53 +0000] [12451] [DEBUG] GET /home
Not Found: /home
[2016-04-09 11:37:59 +0000] [12450] [DEBUG] GET /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 74, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: static/homepage.html
[2016-04-09 11:40:30 +0000] [12447] [DEBUG] GET /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 74, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: static/homepage.html
[2016-04-09 11:40:33 +0000] [12450] [DEBUG] GET /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 74, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: static/homepage.html
[2016-04-09 11:40:42 +0000] [12447] [DEBUG] GET /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 74, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: static/homepage.html
[2016-04-09 11:41:24 +0000] [12441] [INFO] Handling signal: term
[2016-04-09 11:41:24 +0000] [12450] [INFO] Worker exiting (pid: 12450)
[2016-04-09 11:41:24 +0000] [12451] [INFO] Worker exiting (pid: 12451)
[2016-04-09 11:41:24 +0000] [12447] [INFO] Worker exiting (pid: 12447)
[2016-04-09 11:41:24 +0000] [12441] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-09 11:41:25 +0000] [12487] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f110578a410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f110578a140>
  pre_fork: <function pre_fork at 0x7f110578a2a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f11057fff50>
  pre_exec: <function pre_exec at 0x7f110578a9b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f110578a578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f110578f0c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f110578ab18>
  post_request: <function post_request at 0x7f110578ac08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f110578a6e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f110578ad70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f11057ffde8>
  worker_abort: <function worker_abort at 0x7f110578a848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f110578aed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-09 11:41:25 +0000] [12487] [INFO] Starting gunicorn 19.4.5
[2016-04-09 11:41:25 +0000] [12487] [DEBUG] Arbiter booted
[2016-04-09 11:41:25 +0000] [12487] [INFO] Listening at: http://0.0.0.0:8001 (12487)
[2016-04-09 11:41:25 +0000] [12487] [INFO] Using worker: sync
[2016-04-09 11:41:25 +0000] [12493] [INFO] Booting worker with pid: 12493
[2016-04-09 11:41:25 +0000] [12496] [INFO] Booting worker with pid: 12496
[2016-04-09 11:41:25 +0000] [12497] [INFO] Booting worker with pid: 12497
[2016-04-09 11:41:25 +0000] [12487] [DEBUG] 3 workers
[2016-04-09 11:41:28 +0000] [12496] [DEBUG] GET /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 74, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: homepage.html
[2016-04-09 11:41:33 +0000] [12497] [DEBUG] GET /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 74, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: homepage.html
[2016-04-09 11:41:55 +0000] [12496] [DEBUG] GET /home/ubuntu/flurry/logs/nginx-access.log
Not Found: /home/ubuntu/flurry/logs/nginx-access.log
[2016-04-09 11:42:12 +0000] [12493] [DEBUG] GET /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 74, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: homepage.html
[2016-04-09 11:43:16 +0000] [12487] [INFO] Handling signal: term
[2016-04-09 11:43:16 +0000] [12496] [INFO] Worker exiting (pid: 12496)
[2016-04-09 11:43:16 +0000] [12497] [INFO] Worker exiting (pid: 12497)
[2016-04-09 11:43:16 +0000] [12493] [INFO] Worker exiting (pid: 12493)
[2016-04-09 11:43:16 +0000] [12487] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-09 11:43:17 +0000] [12513] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f7fa3225410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f7fa3225140>
  pre_fork: <function pre_fork at 0x7f7fa32252a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f7fa329af50>
  pre_exec: <function pre_exec at 0x7f7fa32259b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f7fa3225578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f7fa322a0c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f7fa3225b18>
  post_request: <function post_request at 0x7f7fa3225c08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f7fa32256e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f7fa3225d70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f7fa329ade8>
  worker_abort: <function worker_abort at 0x7f7fa3225848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f7fa3225ed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-09 11:43:17 +0000] [12513] [INFO] Starting gunicorn 19.4.5
[2016-04-09 11:43:17 +0000] [12513] [DEBUG] Arbiter booted
[2016-04-09 11:43:17 +0000] [12513] [INFO] Listening at: http://0.0.0.0:8001 (12513)
[2016-04-09 11:43:17 +0000] [12513] [INFO] Using worker: sync
[2016-04-09 11:43:17 +0000] [12519] [INFO] Booting worker with pid: 12519
[2016-04-09 11:43:17 +0000] [12520] [INFO] Booting worker with pid: 12520
[2016-04-09 11:43:17 +0000] [12523] [INFO] Booting worker with pid: 12523
[2016-04-09 11:43:17 +0000] [12513] [DEBUG] 3 workers
[2016-04-09 11:43:20 +0000] [12520] [DEBUG] GET /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 74, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: /static/homepage.html
[2016-04-09 11:43:21 +0000] [12523] [DEBUG] GET /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 74, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: /static/homepage.html
[2016-04-09 11:53:35 +0000] [12513] [INFO] Handling signal: term
[2016-04-09 11:53:35 +0000] [12520] [INFO] Worker exiting (pid: 12520)
[2016-04-09 11:53:35 +0000] [12523] [INFO] Worker exiting (pid: 12523)
[2016-04-09 11:53:35 +0000] [12519] [INFO] Worker exiting (pid: 12519)
[2016-04-09 11:53:35 +0000] [12513] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-09 11:53:36 +0000] [12652] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7fe82f78c410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7fe82f78c140>
  pre_fork: <function pre_fork at 0x7fe82f78c2a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7fe82f801f50>
  pre_exec: <function pre_exec at 0x7fe82f78c9b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7fe82f78c578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7fe82f7910c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7fe82f78cb18>
  post_request: <function post_request at 0x7fe82f78cc08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7fe82f78c6e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7fe82f78cd70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7fe82f801de8>
  worker_abort: <function worker_abort at 0x7fe82f78c848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7fe82f78ced8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-09 11:53:36 +0000] [12652] [INFO] Starting gunicorn 19.4.5
[2016-04-09 11:53:36 +0000] [12652] [DEBUG] Arbiter booted
[2016-04-09 11:53:36 +0000] [12652] [INFO] Listening at: http://0.0.0.0:8001 (12652)
[2016-04-09 11:53:36 +0000] [12652] [INFO] Using worker: sync
[2016-04-09 11:53:36 +0000] [12658] [INFO] Booting worker with pid: 12658
[2016-04-09 11:53:36 +0000] [12659] [INFO] Booting worker with pid: 12659
[2016-04-09 11:53:36 +0000] [12664] [INFO] Booting worker with pid: 12664
[2016-04-09 11:53:36 +0000] [12652] [DEBUG] 3 workers
[2016-04-09 11:53:44 +0000] [12659] [DEBUG] GET /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 134, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 374, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/flurry/flurry/urls.py", line 18, in <module>
    import flurryapp.urls
  File "/home/ubuntu/flurry/flurryapp/urls.py", line 21, in <module>
    urlpatterns =[url(r'^$', views.index, name='index')] + router.urls
NameError: name 'views' is not defined
[2016-04-09 11:54:35 +0000] [12652] [INFO] Handling signal: term
[2016-04-09 11:54:35 +0000] [12664] [INFO] Worker exiting (pid: 12664)
[2016-04-09 11:54:35 +0000] [12658] [INFO] Worker exiting (pid: 12658)
[2016-04-09 11:54:35 +0000] [12659] [INFO] Worker exiting (pid: 12659)
[2016-04-09 11:54:35 +0000] [12652] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-09 11:54:37 +0000] [12674] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7fedfcfe4410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7fedfcfe4140>
  pre_fork: <function pre_fork at 0x7fedfcfe42a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7fedfd059f50>
  pre_exec: <function pre_exec at 0x7fedfcfe49b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7fedfcfe4578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7fedfcfe90c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7fedfcfe4b18>
  post_request: <function post_request at 0x7fedfcfe4c08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7fedfcfe46e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7fedfcfe4d70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7fedfd059de8>
  worker_abort: <function worker_abort at 0x7fedfcfe4848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7fedfcfe4ed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-09 11:54:37 +0000] [12674] [INFO] Starting gunicorn 19.4.5
[2016-04-09 11:54:37 +0000] [12674] [DEBUG] Arbiter booted
[2016-04-09 11:54:37 +0000] [12674] [INFO] Listening at: http://0.0.0.0:8001 (12674)
[2016-04-09 11:54:37 +0000] [12674] [INFO] Using worker: sync
[2016-04-09 11:54:37 +0000] [12680] [INFO] Booting worker with pid: 12680
[2016-04-09 11:54:37 +0000] [12681] [INFO] Booting worker with pid: 12681
[2016-04-09 11:54:37 +0000] [12686] [INFO] Booting worker with pid: 12686
[2016-04-09 11:54:37 +0000] [12674] [DEBUG] 3 workers
[2016-04-09 11:54:39 +0000] [12681] [DEBUG] GET /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 134, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 374, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/flurry/flurry/urls.py", line 18, in <module>
    import flurryapp.urls
  File "/home/ubuntu/flurry/flurryapp/urls.py", line 21, in <module>
    urlpatterns =[url(r'^$', views.index, name='index')] + router.urls
NameError: name 'views' is not defined
[2016-04-09 11:54:41 +0000] [12686] [DEBUG] GET /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 134, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 374, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/flurry/flurry/urls.py", line 18, in <module>
    import flurryapp.urls
  File "/home/ubuntu/flurry/flurryapp/urls.py", line 21, in <module>
    urlpatterns =[url(r'^$', views.index, name='index')] + router.urls
NameError: name 'views' is not defined
[2016-04-09 11:55:20 +0000] [12674] [INFO] Handling signal: term
[2016-04-09 11:55:20 +0000] [12680] [INFO] Worker exiting (pid: 12680)
[2016-04-09 11:55:20 +0000] [12681] [INFO] Worker exiting (pid: 12681)
[2016-04-09 11:55:20 +0000] [12686] [INFO] Worker exiting (pid: 12686)
[2016-04-09 11:55:20 +0000] [12674] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-09 11:55:21 +0000] [12708] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7fe9db6da410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7fe9db6da140>
  pre_fork: <function pre_fork at 0x7fe9db6da2a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7fe9db74ff50>
  pre_exec: <function pre_exec at 0x7fe9db6da9b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7fe9db6da578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7fe9db6df0c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7fe9db6dab18>
  post_request: <function post_request at 0x7fe9db6dac08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7fe9db6da6e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7fe9db6dad70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7fe9db74fde8>
  worker_abort: <function worker_abort at 0x7fe9db6da848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7fe9db6daed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-09 11:55:21 +0000] [12708] [INFO] Starting gunicorn 19.4.5
[2016-04-09 11:55:21 +0000] [12708] [DEBUG] Arbiter booted
[2016-04-09 11:55:21 +0000] [12708] [INFO] Listening at: http://0.0.0.0:8001 (12708)
[2016-04-09 11:55:21 +0000] [12708] [INFO] Using worker: sync
[2016-04-09 11:55:21 +0000] [12714] [INFO] Booting worker with pid: 12714
[2016-04-09 11:55:21 +0000] [12715] [INFO] Booting worker with pid: 12715
[2016-04-09 11:55:21 +0000] [12716] [INFO] Booting worker with pid: 12716
[2016-04-09 11:55:21 +0000] [12708] [DEBUG] 3 workers
[2016-04-09 11:55:24 +0000] [12715] [DEBUG] GET /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/flurry/flurryapp/views.py", line 12, in index
    return render(request, html)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 43, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: 
    <p><h3><b>Flurry Project<b><h3><p>

    <br><a href="api/v1/flurry/">API</a></br>
    <br><a href="admin/">Admin Page</a></br>
    
[2016-04-09 11:55:39 +0000] [12716] [DEBUG] GET /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/flurry/flurryapp/views.py", line 12, in index
    return render(request, html)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 43, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: 
    <p><h3><b>Flurry Project<b><h3><p>

    <br><a href="api/v1/flurry/">API</a></br>
    <br><a href="admin/">Admin Page</a></br>
    
[2016-04-09 11:56:43 +0000] [12708] [INFO] Handling signal: term
[2016-04-09 11:56:43 +0000] [12714] [INFO] Worker exiting (pid: 12714)
[2016-04-09 11:56:43 +0000] [12715] [INFO] Worker exiting (pid: 12715)
[2016-04-09 11:56:43 +0000] [12716] [INFO] Worker exiting (pid: 12716)
[2016-04-09 11:56:43 +0000] [12708] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-09 11:56:44 +0000] [12732] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f8c13340410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f8c13340140>
  pre_fork: <function pre_fork at 0x7f8c133402a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f8c133b5f50>
  pre_exec: <function pre_exec at 0x7f8c133409b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f8c13340578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f8c133450c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f8c13340b18>
  post_request: <function post_request at 0x7f8c13340c08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f8c133406e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f8c13340d70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f8c133b5de8>
  worker_abort: <function worker_abort at 0x7f8c13340848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f8c13340ed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-09 11:56:44 +0000] [12732] [INFO] Starting gunicorn 19.4.5
[2016-04-09 11:56:44 +0000] [12732] [DEBUG] Arbiter booted
[2016-04-09 11:56:44 +0000] [12732] [INFO] Listening at: http://0.0.0.0:8001 (12732)
[2016-04-09 11:56:44 +0000] [12732] [INFO] Using worker: sync
[2016-04-09 11:56:44 +0000] [12738] [INFO] Booting worker with pid: 12738
[2016-04-09 11:56:44 +0000] [12741] [INFO] Booting worker with pid: 12741
[2016-04-09 11:56:44 +0000] [12742] [INFO] Booting worker with pid: 12742
[2016-04-09 11:56:44 +0000] [12732] [DEBUG] 3 workers
[2016-04-09 11:56:47 +0000] [12741] [DEBUG] GET /
[2016-04-09 11:56:51 +0000] [12742] [DEBUG] GET /api/v1/flurry/
[2016-04-09 11:56:58 +0000] [12741] [DEBUG] GET /admin/
[2016-04-09 11:56:58 +0000] [12742] [DEBUG] GET /admin/login/
[2016-04-09 11:57:59 +0000] [12738] [DEBUG] GET /admin/
[2016-04-09 11:57:59 +0000] [12742] [DEBUG] GET /admin/login/
[2016-04-09 11:58:05 +0000] [12738] [DEBUG] POST /admin/login/
[2016-04-09 11:58:05 +0000] [12742] [DEBUG] GET /admin/
[2016-04-09 11:59:29 +0000] [12742] [DEBUG] GET /
[2016-04-09 11:59:29 +0000] [12741] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-09 11:59:32 +0000] [12738] [DEBUG] GET /api/v1/flurry/
[2016-04-09 11:59:35 +0000] [12741] [DEBUG] GET /admin/
[2016-04-09 11:59:36 +0000] [12742] [DEBUG] GET /admin/login/
[2016-04-09 12:00:04 +0000] [12741] [DEBUG] GET /
[2016-04-09 12:00:08 +0000] [12738] [DEBUG] GET /api/v1/flurry/
[2016-04-09 12:00:13 +0000] [12742] [DEBUG] GET /api/v1/flurry/cars/
[2016-04-09 12:00:21 +0000] [12738] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-09 12:00:26 +0000] [12741] [DEBUG] GET /api/v1/flurry/profiles/
[2016-04-09 12:00:32 +0000] [12738] [DEBUG] GET /api/v1/flurry/data-drivers/
[2016-04-09 12:01:41 +0000] [12738] [DEBUG] GET /api/v1/flurry/
[2016-04-09 12:02:27 +0000] [12741] [DEBUG] GET /
[2016-04-09 12:02:30 +0000] [12742] [DEBUG] GET /api/v1/flurry/
[2016-04-09 12:02:40 +0000] [12741] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-09 12:02:59 +0000] [12742] [DEBUG] POST /api/v1/flurry/drivers/
[2016-04-09 12:03:14 +0000] [12738] [DEBUG] POST /api/v1/flurry/drivers/
[2016-04-09 12:03:21 +0000] [12741] [DEBUG] POST /api/v1/flurry/drivers/
[2016-04-09 12:03:23 +0000] [12742] [DEBUG] GET /api/v1/flurry/
[2016-04-09 12:03:25 +0000] [12741] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-09 12:03:42 +0000] [12742] [DEBUG] GET /api/v1/flurry/data-drivers/1/
[2016-04-09 12:03:48 +0000] [12741] [DEBUG] GET /api/v1/flurry/data-drivers/3/
[2016-04-09 12:23:31 +0000] [12742] [DEBUG] GET /
[2016-04-09 12:23:31 +0000] [12738] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-09 12:23:34 +0000] [12741] [DEBUG] GET /admin/
[2016-04-09 12:23:35 +0000] [12742] [DEBUG] GET /admin/login/
[2016-04-09 12:23:38 +0000] [12741] [DEBUG] GET /api/v1/flurry/
[2016-04-09 12:29:03 +0000] [12738] [DEBUG] GET /
[2016-04-09 12:29:11 +0000] [12741] [DEBUG] GET /api/v1/flurry/
[2016-04-09 12:29:27 +0000] [12742] [DEBUG] GET /admin/
[2016-04-09 12:29:28 +0000] [12738] [DEBUG] GET /admin/login/
[2016-04-09 12:31:49 +0000] [12742] [DEBUG] GET /
[2016-04-09 12:34:25 +0000] [12738] [DEBUG] GET /
[2016-04-09 12:34:28 +0000] [12741] [DEBUG] GET /admin/
[2016-04-09 12:34:28 +0000] [12742] [DEBUG] GET /admin/login/
[2016-04-09 12:37:47 +0000] [12742] [DEBUG] GET /
[2016-04-09 12:37:47 +0000] [12741] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-09 12:46:53 +0000] [12741] [DEBUG] GET /
[2016-04-09 12:46:53 +0000] [12742] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-09 12:46:57 +0000] [12738] [DEBUG] GET /api/v1/flurry/
[2016-04-09 12:47:17 +0000] [12742] [DEBUG] GET /api/v1/flurry/cars/
[2016-04-09 12:47:48 +0000] [12738] [DEBUG] GET /api/v1/flurry/
[2016-04-09 12:47:52 +0000] [12742] [DEBUG] GET /admin/
[2016-04-09 12:47:52 +0000] [12741] [DEBUG] GET /admin/login/
[2016-04-09 12:48:03 +0000] [12742] [DEBUG] POST /admin/login/
[2016-04-09 12:48:05 +0000] [12741] [DEBUG] GET /admin/login/
[2016-04-09 12:48:07 +0000] [12738] [DEBUG] GET /api/v1/flurry/
[2016-04-09 12:48:12 +0000] [12741] [DEBUG] GET /api/v1/flurry/data-drivers/
[2016-04-09 12:55:35 +0000] [12741] [DEBUG] GET /
[2016-04-09 12:55:35 +0000] [12742] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-09 12:55:36 +0000] [12738] [DEBUG] GET /
[2016-04-09 12:55:37 +0000] [12741] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-09 12:55:39 +0000] [12738] [DEBUG] GET /api/v1/flurry/
[2016-04-09 12:55:49 +0000] [12741] [DEBUG] GET /api/v1/flurry/cars/
[2016-04-09 12:55:54 +0000] [12742] [DEBUG] GET /api/v1/flurry/
[2016-04-09 12:55:58 +0000] [12741] [DEBUG] GET /api/v1/flurry/cars/
[2016-04-09 12:56:09 +0000] [12742] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-09 12:56:15 +0000] [12738] [DEBUG] GET /api/v1/flurry/
[2016-04-09 12:56:19 +0000] [12741] [DEBUG] GET /admin/
[2016-04-09 12:56:19 +0000] [12742] [DEBUG] GET /admin/login/
[2016-04-09 12:58:43 +0000] [12742] [DEBUG] GET /
[2016-04-09 12:58:45 +0000] [12741] [DEBUG] GET /api/v1/flurry/
[2016-04-09 12:58:56 +0000] [12742] [DEBUG] GET /api/v1/flurry/cars/
[2016-04-09 12:59:34 +0000] [12741] [DEBUG] GET /
[2016-04-09 12:59:35 +0000] [12738] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-09 13:00:07 +0000] [12738] [DEBUG] GET /api/v1/flurry/
[2016-04-09 13:01:29 +0000] [12742] [DEBUG] GET /admin/
[2016-04-09 13:01:30 +0000] [12738] [DEBUG] GET /admin/login/
[2016-04-09 13:19:03 +0000] [12738] [DEBUG] GET /api/v1/flurry/
[2016-04-09 13:19:05 +0000] [12741] [DEBUG] GET /api/v1/flurry/cars/
[2016-04-09 13:19:12 +0000] [12738] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-09 13:19:14 +0000] [12741] [DEBUG] GET /api/v1/flurry/data-drivers/
[2016-04-09 13:19:17 +0000] [12738] [DEBUG] GET /api/v1/flurry/data-drivers/
[2016-04-09 13:19:19 +0000] [12741] [DEBUG] GET /api/v1/flurry/profiles/
[2016-04-09 13:23:16 +0000] [12742] [DEBUG] GET /
[2016-04-09 13:23:20 +0000] [12738] [DEBUG] GET /admin/
[2016-04-09 13:23:30 +0000] [12741] [DEBUG] GET /admin/auth/user/
[2016-04-09 13:23:31 +0000] [12738] [DEBUG] GET /admin/jsi18n/
[2016-04-09 13:23:34 +0000] [12742] [DEBUG] GET /admin/auth/user/1/change/
[2016-04-09 13:23:34 +0000] [12738] [DEBUG] GET /admin/jsi18n/
[2016-04-09 13:24:45 +0000] [12738] [DEBUG] GET /admin/auth/user/
[2016-04-09 13:24:50 +0000] [12742] [DEBUG] GET /admin/auth/
[2016-04-09 13:24:52 +0000] [12738] [DEBUG] GET /admin/
[2016-04-09 13:29:49 +0000] [12738] [DEBUG] GET /
[2016-04-09 13:29:49 +0000] [12742] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-09 13:29:50 +0000] [12741] [DEBUG] GET /api/v1/flurry/
[2016-04-09 13:34:32 +0000] [12741] [DEBUG] GET /
[2016-04-09 13:34:32 +0000] [12742] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-09 13:34:35 +0000] [12738] [DEBUG] GET /api/v1/flurry/
[2016-04-09 13:34:39 +0000] [12742] [DEBUG] GET /api/v1/flurry/cars/
[2016-04-09 13:34:41 +0000] [12738] [DEBUG] GET /api/v1/flurry/
[2016-04-09 13:34:44 +0000] [12742] [DEBUG] GET /api/v1/flurry/data-drivers/
[2016-04-09 13:34:47 +0000] [12738] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-09 13:34:53 +0000] [12742] [DEBUG] GET /admin/
[2016-04-09 13:34:53 +0000] [12741] [DEBUG] GET /admin/login/
[2016-04-09 13:34:57 +0000] [12742] [DEBUG] POST /admin/login/
[2016-04-09 13:35:03 +0000] [12741] [DEBUG] POST /admin/login/
[2016-04-09 13:35:08 +0000] [12738] [DEBUG] POST /admin/login/
[2016-04-09 13:35:15 +0000] [12741] [DEBUG] GET /
[2016-04-09 13:43:50 +0000] [12741] [DEBUG] GET /
[2016-04-09 13:44:21 +0000] [12741] [DEBUG] GET /
[2016-04-09 13:44:37 +0000] [12742] [DEBUG] GET /
[2016-04-09 13:44:38 +0000] [12741] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-09 13:44:51 +0000] [12738] [DEBUG] GET /admin/
[2016-04-09 13:44:51 +0000] [12742] [DEBUG] GET /admin/login/
[2016-04-09 13:47:41 +0000] [12738] [DEBUG] GET /
[2016-04-09 13:58:15 +0000] [12741] [DEBUG] GET /
[2016-04-09 13:58:16 +0000] [12738] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-09 13:58:18 +0000] [12742] [DEBUG] GET /api/v1/flurry/
[2016-04-09 13:58:19 +0000] [12738] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-09 13:58:21 +0000] [12741] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-09 14:07:40 +0000] [12741] [DEBUG] GET /manager/html
Not Found: /manager/html
[2016-04-09 17:09:27 +0000] [12741] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-09 17:09:29 +0000] [12738] [DEBUG] GET /
[2016-04-09 17:09:31 +0000] [12742] [DEBUG] GET /api/v1/flurry/
[2016-04-09 17:09:36 +0000] [12738] [DEBUG] GET /api/v1/flurry/cars/
[2016-04-09 17:09:53 +0000] [12742] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-09 17:10:53 +0000] [12738] [DEBUG] GET /api/v1/flurry/data-drivers/
[2016-04-09 17:57:01 +0000] [12742] [DEBUG] GET /testproxy.php
Not Found: /testproxy.php
[2016-04-09 21:16:26 +0000] [12741] [DEBUG] GET /cache/global/img/gs.gif
Not Found: /cache/global/img/gs.gif
[2016-04-10 01:11:08 +0000] [12742] [DEBUG] GET /
[2016-04-10 03:19:24 +0000] [12738] [DEBUG] GET /xmlrpc.php
Not Found: /xmlrpc.php
[2016-04-10 06:51:21 +0000] [12741] [DEBUG] GET /
[2016-04-10 06:51:22 +0000] [12742] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-10 06:51:23 +0000] [12738] [DEBUG] GET /api/v1/flurry/
[2016-04-10 06:51:26 +0000] [12742] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-10 09:37:27 +0000] [12742] [DEBUG] GET /testproxy.php
Not Found: /testproxy.php
[2016-04-10 15:31:28 +0000] [12738] [DEBUG] GET /xmlrpc.php
Not Found: /xmlrpc.php
[2016-04-10 17:45:37 +0000] [12741] [DEBUG] GET /testproxy.php
Not Found: /testproxy.php
[2016-04-11 05:19:05 +0000] [12741] [DEBUG] GET /testproxy.php
Not Found: /testproxy.php
[2016-04-11 07:01:01 +0000] [12742] [DEBUG] HEAD /irj/portal
Not Found: /irj/portal
[2016-04-11 09:26:23 +0000] [12741] [DEBUG] GET /
[2016-04-11 09:26:23 +0000] [12738] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-11 09:26:25 +0000] [12742] [DEBUG] GET /api/v1/flurry/
[2016-04-11 09:26:35 +0000] [12738] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-11 09:26:42 +0000] [12741] [DEBUG] GET /api/v1/flurry/data-drivers/1/
[2016-04-11 09:26:45 +0000] [12742] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-11 09:26:46 +0000] [12741] [DEBUG] GET /api/v1/flurry/
[2016-04-11 09:26:54 +0000] [12742] [DEBUG] GET /api/v1/flurry/cars/
[2016-04-11 09:27:00 +0000] [12738] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-11 09:27:04 +0000] [12742] [DEBUG] GET /admin/
[2016-04-11 09:27:04 +0000] [12741] [DEBUG] GET /admin/login/
[2016-04-11 09:27:09 +0000] [12742] [DEBUG] POST /admin/login/
[2016-04-11 09:27:11 +0000] [12741] [DEBUG] GET /admin/
[2016-04-11 09:27:16 +0000] [12742] [DEBUG] GET /admin/flurryapp/driver/
[2016-04-11 09:27:16 +0000] [12738] [DEBUG] GET /admin/jsi18n/
[2016-04-11 09:27:20 +0000] [12741] [DEBUG] GET /admin/
[2016-04-11 17:18:33 +0000] [12738] [DEBUG] GET /xmlrpc.php
Not Found: /xmlrpc.php
[2016-04-12 00:18:00 +0000] [12738] [DEBUG] GET /testproxy.php
Not Found: /testproxy.php
[2016-04-12 05:10:44 +0000] [12742] [DEBUG] GET /testproxy.php
Not Found: /testproxy.php
[2016-04-12 08:40:02 +0000] [12738] [DEBUG] GET /
[2016-04-12 08:40:02 +0000] [12742] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-12 09:41:34 +0000] [12742] [DEBUG] GET /
[2016-04-12 09:41:34 +0000] [12738] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-12 09:42:10 +0000] [12732] [INFO] Handling signal: term
[2016-04-12 09:42:10 +0000] [12738] [INFO] Worker exiting (pid: 12738)
[2016-04-12 09:42:10 +0000] [12741] [INFO] Worker exiting (pid: 12741)
[2016-04-12 09:42:10 +0000] [12742] [INFO] Worker exiting (pid: 12742)
[2016-04-12 09:42:10 +0000] [12732] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-12 09:42:11 +0000] [28317] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f7172aab410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f7172aab140>
  pre_fork: <function pre_fork at 0x7f7172aab2a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f7172b20f50>
  pre_exec: <function pre_exec at 0x7f7172aab9b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f7172aab578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f7172ab00c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f7172aabb18>
  post_request: <function post_request at 0x7f7172aabc08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f7172aab6e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f7172aabd70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f7172b20de8>
  worker_abort: <function worker_abort at 0x7f7172aab848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f7172aabed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-12 09:42:11 +0000] [28317] [INFO] Starting gunicorn 19.4.5
[2016-04-12 09:42:11 +0000] [28317] [DEBUG] Arbiter booted
[2016-04-12 09:42:11 +0000] [28317] [INFO] Listening at: http://0.0.0.0:8001 (28317)
[2016-04-12 09:42:11 +0000] [28317] [INFO] Using worker: sync
[2016-04-12 09:42:11 +0000] [28323] [INFO] Booting worker with pid: 28323
[2016-04-12 09:42:11 +0000] [28326] [INFO] Booting worker with pid: 28326
[2016-04-12 09:42:11 +0000] [28327] [INFO] Booting worker with pid: 28327
[2016-04-12 09:42:11 +0000] [28317] [DEBUG] 3 workers
[2016-04-12 09:42:14 +0000] [28326] [DEBUG] GET /
[2016-04-12 09:42:16 +0000] [28327] [DEBUG] GET /
[2016-04-12 09:43:59 +0000] [28323] [DEBUG] GET /api/v1/flurry/
[2016-04-12 09:44:17 +0000] [28327] [DEBUG] GET /
[2016-04-12 09:46:04 +0000] [28323] [DEBUG] GET /
[2016-04-12 09:48:56 +0000] [28317] [INFO] Handling signal: term
[2016-04-12 09:48:56 +0000] [28323] [INFO] Worker exiting (pid: 28323)
[2016-04-12 09:48:56 +0000] [28326] [INFO] Worker exiting (pid: 28326)
[2016-04-12 09:48:56 +0000] [28327] [INFO] Worker exiting (pid: 28327)
[2016-04-12 09:48:56 +0000] [28317] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-12 09:48:57 +0000] [28461] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f63d9dc9410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f63d9dc9140>
  pre_fork: <function pre_fork at 0x7f63d9dc92a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f63d9e3ef50>
  pre_exec: <function pre_exec at 0x7f63d9dc99b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f63d9dc9578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f63d9dce0c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f63d9dc9b18>
  post_request: <function post_request at 0x7f63d9dc9c08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f63d9dc96e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f63d9dc9d70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f63d9e3ede8>
  worker_abort: <function worker_abort at 0x7f63d9dc9848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f63d9dc9ed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-12 09:48:57 +0000] [28461] [INFO] Starting gunicorn 19.4.5
[2016-04-12 09:48:57 +0000] [28461] [DEBUG] Arbiter booted
[2016-04-12 09:48:57 +0000] [28461] [INFO] Listening at: http://0.0.0.0:8001 (28461)
[2016-04-12 09:48:57 +0000] [28461] [INFO] Using worker: sync
[2016-04-12 09:48:57 +0000] [28467] [INFO] Booting worker with pid: 28467
[2016-04-12 09:48:57 +0000] [28470] [INFO] Booting worker with pid: 28470
[2016-04-12 09:48:57 +0000] [28471] [INFO] Booting worker with pid: 28471
[2016-04-12 09:48:57 +0000] [28461] [DEBUG] 3 workers
[2016-04-12 09:49:01 +0000] [28470] [DEBUG] GET /
[2016-04-12 09:53:16 +0000] [28461] [INFO] Handling signal: term
[2016-04-12 09:53:16 +0000] [28467] [INFO] Worker exiting (pid: 28467)
[2016-04-12 09:53:16 +0000] [28470] [INFO] Worker exiting (pid: 28470)
[2016-04-12 09:53:16 +0000] [28471] [INFO] Worker exiting (pid: 28471)
[2016-04-12 09:53:16 +0000] [28461] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-12 09:53:17 +0000] [28526] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7fe161d02410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7fe161d02140>
  pre_fork: <function pre_fork at 0x7fe161d022a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7fe161d77f50>
  pre_exec: <function pre_exec at 0x7fe161d029b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7fe161d02578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7fe161d070c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7fe161d02b18>
  post_request: <function post_request at 0x7fe161d02c08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7fe161d026e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7fe161d02d70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7fe161d77de8>
  worker_abort: <function worker_abort at 0x7fe161d02848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7fe161d02ed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-12 09:53:17 +0000] [28526] [INFO] Starting gunicorn 19.4.5
[2016-04-12 09:53:17 +0000] [28526] [DEBUG] Arbiter booted
[2016-04-12 09:53:17 +0000] [28526] [INFO] Listening at: http://0.0.0.0:8001 (28526)
[2016-04-12 09:53:17 +0000] [28526] [INFO] Using worker: sync
[2016-04-12 09:53:17 +0000] [28532] [INFO] Booting worker with pid: 28532
[2016-04-12 09:53:17 +0000] [28535] [INFO] Booting worker with pid: 28535
[2016-04-12 09:53:17 +0000] [28526] [DEBUG] 3 workers
[2016-04-12 09:53:17 +0000] [28536] [INFO] Booting worker with pid: 28536
[2016-04-12 09:53:20 +0000] [28535] [DEBUG] GET /
[2016-04-12 09:53:23 +0000] [28536] [DEBUG] GET /
[2016-04-12 09:53:25 +0000] [28535] [DEBUG] GET /
[2016-04-12 09:53:26 +0000] [28532] [DEBUG] GET /
[2016-04-12 09:53:27 +0000] [28535] [DEBUG] GET /
[2016-04-12 09:53:35 +0000] [28536] [DEBUG] GET /
[2016-04-12 09:53:37 +0000] [28536] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-12 09:54:39 +0000] [28536] [DEBUG] GET /api/v1/flurry/
[2016-04-12 09:54:42 +0000] [28532] [DEBUG] GET /admin/
[2016-04-12 09:56:07 +0000] [28532] [DEBUG] GET /
[2016-04-12 09:58:55 +0000] [28532] [DEBUG] GET /
[2016-04-12 10:00:11 +0000] [28532] [DEBUG] GET /
[2016-04-12 10:00:16 +0000] [28535] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-12 10:00:30 +0000] [28536] [DEBUG] GET /
[2016-04-12 10:02:31 +0000] [28536] [DEBUG] GET /
[2016-04-12 10:02:34 +0000] [28535] [DEBUG] GET /
[2016-04-12 10:02:37 +0000] [28532] [DEBUG] GET /
[2016-04-12 10:02:39 +0000] [28535] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-12 10:02:45 +0000] [28536] [DEBUG] GET /
[2016-04-12 10:07:35 +0000] [28536] [DEBUG] GET /
[2016-04-12 10:07:35 +0000] [28535] [DEBUG] GET /static/node_modules/materialize-css/dist/css/materialize.css
[2016-04-12 10:07:35 +0000] [28532] [DEBUG] GET /static/asaf.css
Not Found: /static/asaf.css
Not Found: /static/node_modules/materialize-css/dist/css/materialize.css
[2016-04-12 10:07:35 +0000] [28536] [DEBUG] GET /static/node_modules/jquery/dist/jquery.js
Not Found: /static/node_modules/jquery/dist/jquery.js
[2016-04-12 10:07:35 +0000] [28532] [DEBUG] GET /static/node_modules/materialize-css/dist/js/materialize.js
Not Found: /static/node_modules/materialize-css/dist/js/materialize.js
[2016-04-12 10:07:37 +0000] [28535] [DEBUG] GET /
[2016-04-12 10:07:37 +0000] [28536] [DEBUG] GET /static/node_modules/materialize-css/dist/css/materialize.css
Not Found: /static/node_modules/materialize-css/dist/css/materialize.css
[2016-04-12 10:07:37 +0000] [28535] [DEBUG] GET /static/node_modules/jquery/dist/jquery.js
Not Found: /static/node_modules/jquery/dist/jquery.js
[2016-04-12 10:07:37 +0000] [28532] [DEBUG] GET /static/node_modules/materialize-css/dist/js/materialize.js
Not Found: /static/node_modules/materialize-css/dist/js/materialize.js
[2016-04-12 10:07:37 +0000] [28536] [DEBUG] GET /static/asaf.css
Not Found: /static/asaf.css
[2016-04-12 10:07:37 +0000] [28535] [DEBUG] GET /static/logo_michlala_eng_White.png
Not Found: /static/logo_michlala_eng_White.png
[2016-04-12 10:07:37 +0000] [28535] [DEBUG] Ignoring EPIPE
[2016-04-12 10:07:38 +0000] [28532] [DEBUG] GET /static/logo_michlala_eng_White.png
Not Found: /static/logo_michlala_eng_White.png
[2016-04-12 10:07:39 +0000] [28536] [DEBUG] GET /static/asaf.css
Not Found: /static/asaf.css
[2016-04-12 10:07:39 +0000] [28535] [DEBUG] GET /static/node_modules/materialize-css/dist/css/materialize.css
Not Found: /static/node_modules/materialize-css/dist/css/materialize.css
[2016-04-12 10:07:58 +0000] [28532] [DEBUG] GET /
[2016-04-12 10:07:59 +0000] [28532] [DEBUG] GET /static/node_modules/materialize-css/dist/css/materialize.css
Not Found: /static/node_modules/materialize-css/dist/css/materialize.css
[2016-04-12 10:07:59 +0000] [28536] [DEBUG] GET /static/asaf.css
Not Found: /static/asaf.css
[2016-04-12 10:07:59 +0000] [28535] [DEBUG] GET /static/node_modules/jquery/dist/jquery.js
Not Found: /static/node_modules/jquery/dist/jquery.js
[2016-04-12 10:07:59 +0000] [28532] [DEBUG] GET /static/node_modules/materialize-css/dist/js/materialize.js
Not Found: /static/node_modules/materialize-css/dist/js/materialize.js
[2016-04-12 10:07:59 +0000] [28536] [DEBUG] GET /static/logo_michlala_eng_White.png
Not Found: /static/logo_michlala_eng_White.png
[2016-04-12 10:08:36 +0000] [28535] [DEBUG] GET /
[2016-04-12 14:52:25 +0000] [28536] [DEBUG] GET /
[2016-04-12 14:52:26 +0000] [28535] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-12 16:14:23 +0000] [28532] [DEBUG] GET /
[2016-04-12 16:41:35 +0000] [28535] [DEBUG] GET /
[2016-04-12 16:57:56 +0000] [28535] [DEBUG] GET /
[2016-04-12 16:58:00 +0000] [28532] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-12 16:58:08 +0000] [28532] [DEBUG] GET /
[2016-04-12 16:58:31 +0000] [28536] [DEBUG] GET /api/v1/flurry/
[2016-04-12 16:58:36 +0000] [28535] [DEBUG] GET /admin/
[2016-04-12 16:58:36 +0000] [28536] [DEBUG] GET /admin/login/
[2016-04-12 18:09:54 +0000] [28536] [DEBUG] GET /
[2016-04-12 18:09:56 +0000] [28535] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-12 18:12:06 +0000] [28535] [DEBUG] GET /
[2016-04-12 20:33:28 +0000] [28532] [DEBUG] GET /xmlrpc.php
Not Found: /xmlrpc.php
[2016-04-12 23:27:49 +0000] [28532] [DEBUG] GET /xmlrpc.php
Not Found: /xmlrpc.php
[2016-04-13 03:11:35 +0000] [28532] [DEBUG] GET /testproxy.php
Not Found: /testproxy.php
[2016-04-13 04:45:28 +0000] [28532] [DEBUG] GET /
[2016-04-13 05:39:46 +0000] [28536] [DEBUG] GET /
[2016-04-13 05:39:50 +0000] [28532] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-13 05:49:27 +0000] [28532] [DEBUG] GET /api/v1/flurry/
[2016-04-13 05:58:21 +0000] [28536] [DEBUG] GET /
[2016-04-13 06:45:35 +0000] [28532] [DEBUG] GET /testproxy.php
Not Found: /testproxy.php
[2016-04-13 08:32:39 +0000] [28535] [DEBUG] GET /
[2016-04-13 08:33:09 +0000] [28536] [DEBUG] GET /api/v1/flurry/
[2016-04-13 08:33:19 +0000] [28535] [DEBUG] GET /api/v1/flurry/cars/
[2016-04-13 08:33:23 +0000] [28532] [DEBUG] GET /api/v1/flurry/
[2016-04-13 08:33:24 +0000] [28535] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-13 08:33:28 +0000] [28536] [DEBUG] GET /api/v1/flurry/cars/
[2016-04-13 08:33:34 +0000] [28535] [DEBUG] GET /admin/
[2016-04-13 08:33:34 +0000] [28532] [DEBUG] GET /admin/login/
[2016-04-13 12:50:30 +0000] [28535] [DEBUG] GET /
[2016-04-14 02:07:44 +0000] [28532] [DEBUG] GET /
[2016-04-14 05:36:31 +0000] [28536] [DEBUG] GET /
[2016-04-14 08:38:23 +0000] [28536] [DEBUG] GET /manager/html
Not Found: /manager/html
[2016-04-14 11:46:44 +0000] [28535] [DEBUG] GET /
[2016-04-14 11:46:46 +0000] [28536] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-14 11:50:20 +0000] [28526] [INFO] Handling signal: term
[2016-04-14 11:50:20 +0000] [28536] [INFO] Worker exiting (pid: 28536)
[2016-04-14 11:50:20 +0000] [28532] [INFO] Worker exiting (pid: 28532)
[2016-04-14 11:50:20 +0000] [28535] [INFO] Worker exiting (pid: 28535)
[2016-04-14 11:50:20 +0000] [28526] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-14 11:50:21 +0000] [6437] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f7bb17da410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f7bb17da140>
  pre_fork: <function pre_fork at 0x7f7bb17da2a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f7bb184ff50>
  pre_exec: <function pre_exec at 0x7f7bb17da9b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f7bb17da578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f7bb17df0c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f7bb17dab18>
  post_request: <function post_request at 0x7f7bb17dac08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f7bb17da6e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f7bb17dad70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f7bb184fde8>
  worker_abort: <function worker_abort at 0x7f7bb17da848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f7bb17daed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-14 11:50:21 +0000] [6437] [INFO] Starting gunicorn 19.4.5
[2016-04-14 11:50:21 +0000] [6437] [DEBUG] Arbiter booted
[2016-04-14 11:50:21 +0000] [6437] [INFO] Listening at: http://0.0.0.0:8001 (6437)
[2016-04-14 11:50:21 +0000] [6437] [INFO] Using worker: sync
[2016-04-14 11:50:21 +0000] [6443] [INFO] Booting worker with pid: 6443
[2016-04-14 11:50:21 +0000] [6444] [INFO] Booting worker with pid: 6444
[2016-04-14 11:50:21 +0000] [6449] [INFO] Booting worker with pid: 6449
[2016-04-14 11:50:21 +0000] [6437] [DEBUG] 3 workers
[2016-04-14 11:50:24 +0000] [6444] [DEBUG] GET /
[2016-04-14 11:51:42 +0000] [6437] [INFO] Handling signal: term
[2016-04-14 11:51:42 +0000] [6449] [INFO] Worker exiting (pid: 6449)
[2016-04-14 11:51:42 +0000] [6443] [INFO] Worker exiting (pid: 6443)
[2016-04-14 11:51:42 +0000] [6444] [INFO] Worker exiting (pid: 6444)
[2016-04-14 11:51:42 +0000] [6437] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-14 11:51:43 +0000] [6597] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f69a2372410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f69a2372140>
  pre_fork: <function pre_fork at 0x7f69a23722a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f69a23e7f50>
  pre_exec: <function pre_exec at 0x7f69a23729b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f69a2372578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f69a23770c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f69a2372b18>
  post_request: <function post_request at 0x7f69a2372c08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f69a23726e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f69a2372d70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f69a23e7de8>
  worker_abort: <function worker_abort at 0x7f69a2372848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f69a2372ed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-14 11:51:43 +0000] [6597] [INFO] Starting gunicorn 19.4.5
[2016-04-14 11:51:43 +0000] [6597] [DEBUG] Arbiter booted
[2016-04-14 11:51:43 +0000] [6597] [INFO] Listening at: http://0.0.0.0:8001 (6597)
[2016-04-14 11:51:43 +0000] [6597] [INFO] Using worker: sync
[2016-04-14 11:51:43 +0000] [6603] [INFO] Booting worker with pid: 6603
[2016-04-14 11:51:43 +0000] [6604] [INFO] Booting worker with pid: 6604
[2016-04-14 11:51:43 +0000] [6607] [INFO] Booting worker with pid: 6607
[2016-04-14 11:51:43 +0000] [6597] [DEBUG] 3 workers
[2016-04-14 11:51:45 +0000] [6604] [DEBUG] GET /
[2016-04-14 11:52:00 +0000] [6607] [DEBUG] GET /api/v1/flurry/
[2016-04-14 11:52:08 +0000] [6604] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-14 11:52:14 +0000] [6607] [DEBUG] GET /api/v1/flurry/data-drivers/1/
[2016-04-14 11:52:18 +0000] [6603] [DEBUG] GET /api/v1/flurry/data-drivers/2/
[2016-04-14 11:52:22 +0000] [6607] [DEBUG] GET /admin/
[2016-04-14 11:53:46 +0000] [6604] [DEBUG] GET /
[2016-04-14 11:53:54 +0000] [6603] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-14 11:54:11 +0000] [6607] [DEBUG] GET /
[2016-04-14 11:54:15 +0000] [6604] [DEBUG] GET /
[2016-04-14 11:55:36 +0000] [6604] [DEBUG] GET /
[2016-04-14 12:00:03 +0000] [6607] [DEBUG] GET /muieblackcat
Not Found: /muieblackcat
[2016-04-14 12:00:03 +0000] [6603] [DEBUG] GET /admin/scripts/setup.php
Not Found: /admin/scripts/setup.php
[2016-04-14 12:00:03 +0000] [6604] [DEBUG] GET /dbadmin/scripts/setup.php
Not Found: /dbadmin/scripts/setup.php
[2016-04-14 12:00:05 +0000] [6607] [DEBUG] GET /myadmin/scripts/setup.php
Not Found: /myadmin/scripts/setup.php
[2016-04-14 12:00:05 +0000] [6603] [DEBUG] GET /MyAdmin/scripts/setup.php
Not Found: /MyAdmin/scripts/setup.php
[2016-04-14 12:00:05 +0000] [6604] [DEBUG] GET /mysqladmin/scripts/setup.php
Not Found: /mysqladmin/scripts/setup.php
[2016-04-14 12:00:05 +0000] [6607] [DEBUG] GET /mysql/scripts/setup.php
Not Found: /mysql/scripts/setup.php
[2016-04-14 12:00:06 +0000] [6603] [DEBUG] GET /phpma/scripts/setup.php
Not Found: /phpma/scripts/setup.php
[2016-04-14 12:00:06 +0000] [6604] [DEBUG] GET /phpmyadmin/scripts/setup.php
Not Found: /phpmyadmin/scripts/setup.php
[2016-04-14 12:00:06 +0000] [6607] [DEBUG] GET /phpMyAdmin/scripts/setup.php
Not Found: /phpMyAdmin/scripts/setup.php
[2016-04-14 12:00:07 +0000] [6603] [DEBUG] GET /phpMyAdmin/scripts/setup.php
Not Found: /phpMyAdmin/scripts/setup.php
[2016-04-14 12:00:07 +0000] [6604] [DEBUG] GET /pma/scripts/setup.php
Not Found: /pma/scripts/setup.php
[2016-04-14 12:00:07 +0000] [6607] [DEBUG] GET /sqlweb/scripts/setup.php
Not Found: /sqlweb/scripts/setup.php
[2016-04-14 12:00:07 +0000] [6603] [DEBUG] GET /webdb/scripts/setup.php
Not Found: /webdb/scripts/setup.php
[2016-04-14 12:00:08 +0000] [6604] [DEBUG] GET /websql/scripts/setup.php
Not Found: /websql/scripts/setup.php
[2016-04-14 12:39:44 +0000] [6604] [DEBUG] GET /search/complete
Not Found: /search/complete
[2016-04-14 13:29:16 +0000] [6603] [DEBUG] GET /testproxy.php
Not Found: /testproxy.php
[2016-04-14 14:01:03 +0000] [6607] [DEBUG] GET /manager/html
Not Found: /manager/html
[2016-04-14 14:05:13 +0000] [6604] [DEBUG] GET /
[2016-04-14 14:05:14 +0000] [6607] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-14 14:05:48 +0000] [6607] [DEBUG] GET /api/v1/flurry/
[2016-04-14 14:05:58 +0000] [6603] [DEBUG] GET /api/v1/flurry/profiles/
[2016-04-14 14:06:03 +0000] [6607] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-14 14:06:14 +0000] [6603] [DEBUG] GET /api/v1/flurry/cars/
[2016-04-14 14:06:22 +0000] [6607] [DEBUG] GET /api/v1/flurry/profiles/
[2016-04-14 14:06:29 +0000] [6604] [DEBUG] GET /api/v1/flurry/data-drivers/
[2016-04-14 14:21:04 +0000] [6604] [DEBUG] GET /testproxy.php
Not Found: /testproxy.php
[2016-04-14 14:55:47 +0000] [6607] [DEBUG] GET /
[2016-04-14 16:47:04 +0000] [6604] [DEBUG] GET /cgi-bin/test-cgi
Not Found: /cgi-bin/test-cgi
[2016-04-14 16:47:04 +0000] [6604] [DEBUG] Ignoring EPIPE
[2016-04-14 17:20:26 +0000] [6603] [DEBUG] GET /
[2016-04-14 17:20:27 +0000] [6607] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-14 18:06:47 +0000] [6607] [DEBUG] GET /
[2016-04-14 18:06:47 +0000] [6607] [DEBUG] Ignoring EPIPE
[2016-04-14 18:14:53 +0000] [6607] [DEBUG] GET /robots.txt
Not Found: /robots.txt
[2016-04-14 19:12:24 +0000] [6603] [DEBUG] GET /cgi-sys/defaultwebpage.cgi
Not Found: /cgi-sys/defaultwebpage.cgi
[2016-04-14 19:12:24 +0000] [6603] [DEBUG] Ignoring EPIPE
[2016-04-14 21:47:15 +0000] [6604] [DEBUG] GET /test.cgi
Not Found: /test.cgi
[2016-04-14 21:47:15 +0000] [6604] [DEBUG] Ignoring EPIPE
[2016-04-15 05:55:38 +0000] [6607] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-15 06:04:29 +0000] [6603] [DEBUG] GET /cgi-bin/index.cgi
Not Found: /cgi-bin/index.cgi
[2016-04-15 06:04:29 +0000] [6603] [DEBUG] Ignoring EPIPE
[2016-04-15 07:51:22 +0000] [6603] [DEBUG] GET /
[2016-04-15 07:51:25 +0000] [6604] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-15 07:52:53 +0000] [6607] [DEBUG] GET /api/v1/flurry/
[2016-04-15 07:53:00 +0000] [6603] [DEBUG] GET /admin/
[2016-04-15 08:07:26 +0000] [6597] [INFO] Handling signal: term
[2016-04-15 08:07:26 +0000] [6603] [INFO] Worker exiting (pid: 6603)
[2016-04-15 08:07:26 +0000] [6604] [INFO] Worker exiting (pid: 6604)
[2016-04-15 08:07:26 +0000] [6607] [INFO] Worker exiting (pid: 6607)
[2016-04-15 08:07:26 +0000] [6597] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-15 08:07:27 +0000] [10818] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f3db4aac410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f3db4aac140>
  pre_fork: <function pre_fork at 0x7f3db4aac2a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f3db4b21f50>
  pre_exec: <function pre_exec at 0x7f3db4aac9b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f3db4aac578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f3db4ab10c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f3db4aacb18>
  post_request: <function post_request at 0x7f3db4aacc08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f3db4aac6e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f3db4aacd70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f3db4b21de8>
  worker_abort: <function worker_abort at 0x7f3db4aac848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f3db4aaced8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-15 08:07:27 +0000] [10818] [INFO] Starting gunicorn 19.4.5
[2016-04-15 08:07:27 +0000] [10818] [DEBUG] Arbiter booted
[2016-04-15 08:07:27 +0000] [10818] [INFO] Listening at: http://0.0.0.0:8001 (10818)
[2016-04-15 08:07:27 +0000] [10818] [INFO] Using worker: sync
[2016-04-15 08:07:27 +0000] [10824] [INFO] Booting worker with pid: 10824
[2016-04-15 08:07:27 +0000] [10827] [INFO] Booting worker with pid: 10827
[2016-04-15 08:07:27 +0000] [10828] [INFO] Booting worker with pid: 10828
[2016-04-15 08:07:27 +0000] [10818] [DEBUG] 3 workers
[2016-04-15 08:07:30 +0000] [10827] [DEBUG] GET /
[2016-04-15 08:07:32 +0000] [10828] [DEBUG] GET /api/v1/flurry/
[2016-04-15 08:07:36 +0000] [10827] [DEBUG] GET /admin/
[2016-04-15 09:05:36 +0000] [10818] [INFO] Handling signal: term
[2016-04-15 09:05:36 +0000] [10824] [INFO] Worker exiting (pid: 10824)
[2016-04-15 09:05:36 +0000] [10827] [INFO] Worker exiting (pid: 10827)
[2016-04-15 09:05:36 +0000] [10828] [INFO] Worker exiting (pid: 10828)
[2016-04-15 09:05:36 +0000] [10818] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-15 09:05:37 +0000] [11267] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f24d25ff410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f24d25ff140>
  pre_fork: <function pre_fork at 0x7f24d25ff2a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f24d2674f50>
  pre_exec: <function pre_exec at 0x7f24d25ff9b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f24d25ff578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f24d26040c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f24d25ffb18>
  post_request: <function post_request at 0x7f24d25ffc08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f24d25ff6e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f24d25ffd70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f24d2674de8>
  worker_abort: <function worker_abort at 0x7f24d25ff848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f24d25ffed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-15 09:05:37 +0000] [11267] [INFO] Starting gunicorn 19.4.5
[2016-04-15 09:05:37 +0000] [11267] [DEBUG] Arbiter booted
[2016-04-15 09:05:37 +0000] [11267] [INFO] Listening at: http://0.0.0.0:8001 (11267)
[2016-04-15 09:05:37 +0000] [11267] [INFO] Using worker: sync
[2016-04-15 09:05:37 +0000] [11273] [INFO] Booting worker with pid: 11273
[2016-04-15 09:05:37 +0000] [11276] [INFO] Booting worker with pid: 11276
[2016-04-15 09:05:38 +0000] [11277] [INFO] Booting worker with pid: 11277
[2016-04-15 09:05:38 +0000] [11267] [DEBUG] 3 workers
[2016-04-15 09:13:47 +0000] [11277] [DEBUG] GET /
[2016-04-15 09:13:49 +0000] [11276] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-04-15 09:13:58 +0000] [11277] [DEBUG] GET /api/v1/flurry/
[2016-04-15 09:14:02 +0000] [11276] [DEBUG] GET /api/v1/flurry/data-drivers/
[2016-04-15 09:15:21 +0000] [11277] [DEBUG] GET /api/v1/flurry/
[2016-04-15 09:15:23 +0000] [11276] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-15 09:15:41 +0000] [11273] [DEBUG] GET /api/v1/flurry/drivers/2/
[2016-04-15 09:21:23 +0000] [11273] [DEBUG] POST /api/v1/flurry/drivers/2/insert_driving_data/
[2016-04-15 09:21:40 +0000] [11277] [DEBUG] GET /api/v1/flurry/drivers/2/
[2016-04-15 09:21:41 +0000] [11276] [DEBUG] GET /api/v1/flurry/drivers/2/
[2016-04-15 09:21:43 +0000] [11273] [DEBUG] GET /api/v1/flurry/data-drivers/2/
[2016-04-15 09:22:19 +0000] [11277] [DEBUG] PUT /api/v1/flurry/data-drivers/2/
[2016-04-15 09:24:16 +0000] [11273] [DEBUG] GET /api/v1/flurry/data-drivers/2/
[2016-04-15 09:37:49 +0000] [11273] [DEBUG] GET /api/v1/flurry/
[2016-04-15 09:48:21 +0000] [11276] [DEBUG] GET /status.cgi
Not Found: /status.cgi
[2016-04-15 09:48:21 +0000] [11276] [DEBUG] Ignoring EPIPE
[2016-04-15 10:27:31 +0000] [11267] [INFO] Handling signal: term
[2016-04-15 10:27:31 +0000] [11273] [INFO] Worker exiting (pid: 11273)
<QueryDict: {u'test': [u'test']}>
[2016-04-15 10:27:31 +0000] [11276] [INFO] Worker exiting (pid: 11276)
[2016-04-15 10:27:31 +0000] [11277] [INFO] Worker exiting (pid: 11277)
[2016-04-15 10:27:31 +0000] [11267] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-15 10:27:32 +0000] [11818] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f453b504410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f453b504140>
  pre_fork: <function pre_fork at 0x7f453b5042a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f453b579f50>
  pre_exec: <function pre_exec at 0x7f453b5049b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f453b504578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f453b5090c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f453b504b18>
  post_request: <function post_request at 0x7f453b504c08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f453b5046e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f453b504d70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f453b579de8>
  worker_abort: <function worker_abort at 0x7f453b504848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f453b504ed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-15 10:27:32 +0000] [11818] [INFO] Starting gunicorn 19.4.5
[2016-04-15 10:27:32 +0000] [11818] [DEBUG] Arbiter booted
[2016-04-15 10:27:32 +0000] [11818] [INFO] Listening at: http://0.0.0.0:8001 (11818)
[2016-04-15 10:27:32 +0000] [11818] [INFO] Using worker: sync
[2016-04-15 10:27:32 +0000] [11824] [INFO] Booting worker with pid: 11824
[2016-04-15 10:27:32 +0000] [11827] [INFO] Booting worker with pid: 11827
[2016-04-15 10:27:33 +0000] [11830] [INFO] Booting worker with pid: 11830
[2016-04-15 10:27:33 +0000] [11818] [DEBUG] 3 workers
[2016-04-15 10:27:37 +0000] [11827] [DEBUG] GET /api/v1/flurry/
[2016-04-15 10:27:40 +0000] [11830] [DEBUG] GET /api/v1/flurry/users/
Internal Server Error: /api/v1/flurry/users/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 48, in list
    return Response(serializer.data)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 674, in data
    ret = super(ListSerializer, self).data
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 239, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 614, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 459, in to_representation
    fields = self._readable_fields
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 353, in _readable_fields
    field for field in self.fields.values()
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 339, in fields
    for key, value in self.get_fields().items():
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 919, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 1018, in get_field_names
    serializer_class=self.__class__.__name__
AssertionError: The field 'snippets' was declared on serializer UserSerializer, but has not been included in the 'fields' option.
[2016-04-15 10:30:01 +0000] [11818] [INFO] Handling signal: term
[2016-04-15 10:30:01 +0000] [11824] [INFO] Worker exiting (pid: 11824)
[2016-04-15 10:30:01 +0000] [11827] [INFO] Worker exiting (pid: 11827)
[2016-04-15 10:30:01 +0000] [11830] [INFO] Worker exiting (pid: 11830)
[2016-04-15 10:30:01 +0000] [11818] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-15 10:30:02 +0000] [11898] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f3bb9363410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f3bb9363140>
  pre_fork: <function pre_fork at 0x7f3bb93632a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f3bb93d8f50>
  pre_exec: <function pre_exec at 0x7f3bb93639b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f3bb9363578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f3bb93680c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f3bb9363b18>
  post_request: <function post_request at 0x7f3bb9363c08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f3bb93636e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f3bb9363d70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f3bb93d8de8>
  worker_abort: <function worker_abort at 0x7f3bb9363848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f3bb9363ed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-15 10:30:02 +0000] [11898] [INFO] Starting gunicorn 19.4.5
[2016-04-15 10:30:02 +0000] [11898] [DEBUG] Arbiter booted
[2016-04-15 10:30:02 +0000] [11898] [INFO] Listening at: http://0.0.0.0:8001 (11898)
[2016-04-15 10:30:02 +0000] [11898] [INFO] Using worker: sync
[2016-04-15 10:30:02 +0000] [11904] [INFO] Booting worker with pid: 11904
[2016-04-15 10:30:02 +0000] [11907] [INFO] Booting worker with pid: 11907
[2016-04-15 10:30:02 +0000] [11910] [INFO] Booting worker with pid: 11910
[2016-04-15 10:30:02 +0000] [11898] [DEBUG] 3 workers
[2016-04-15 10:30:05 +0000] [11907] [DEBUG] GET /api/v1/flurry/users/
Internal Server Error: /api/v1/flurry/users/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 48, in list
    return Response(serializer.data)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 674, in data
    ret = super(ListSerializer, self).data
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 239, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 614, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 463, in to_representation
    attribute = field.get_attribute(instance)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/relations.py", line 146, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 80, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'User' object has no attribute 'driver'
[2016-04-15 10:35:00 +0000] [11898] [INFO] Handling signal: term
[2016-04-15 10:35:00 +0000] [11904] [INFO] Worker exiting (pid: 11904)
[2016-04-15 10:35:00 +0000] [11907] [INFO] Worker exiting (pid: 11907)
[2016-04-15 10:35:00 +0000] [11910] [INFO] Worker exiting (pid: 11910)
[2016-04-15 10:35:00 +0000] [11898] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-15 10:35:01 +0000] [11972] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f2da50e8410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f2da50e8140>
  pre_fork: <function pre_fork at 0x7f2da50e82a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f2da515df50>
  pre_exec: <function pre_exec at 0x7f2da50e89b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f2da50e8578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f2da50ed0c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f2da50e8b18>
  post_request: <function post_request at 0x7f2da50e8c08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f2da50e86e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f2da50e8d70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f2da515dde8>
  worker_abort: <function worker_abort at 0x7f2da50e8848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f2da50e8ed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-15 10:35:01 +0000] [11972] [INFO] Starting gunicorn 19.4.5
[2016-04-15 10:35:01 +0000] [11972] [DEBUG] Arbiter booted
[2016-04-15 10:35:01 +0000] [11972] [INFO] Listening at: http://0.0.0.0:8001 (11972)
[2016-04-15 10:35:01 +0000] [11972] [INFO] Using worker: sync
[2016-04-15 10:35:01 +0000] [11978] [INFO] Booting worker with pid: 11978
[2016-04-15 10:35:01 +0000] [11981] [INFO] Booting worker with pid: 11981
[2016-04-15 10:35:01 +0000] [11982] [INFO] Booting worker with pid: 11982
[2016-04-15 10:35:01 +0000] [11972] [DEBUG] 3 workers
[2016-04-15 10:35:04 +0000] [11981] [DEBUG] GET /api/v1/flurry/users/
Internal Server Error: /api/v1/flurry/users/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 134, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 374, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/flurry/flurry/urls.py", line 18, in <module>
    import flurryapp.urls
  File "/home/ubuntu/flurry/flurryapp/urls.py", line 2, in <module>
    from flurryapp import viewsets
  File "/home/ubuntu/flurry/flurryapp/viewsets/__init__.py", line 5, in <module>
    from user_viewset import UserViewSet
  File "/home/ubuntu/flurry/flurryapp/viewsets/user_viewset.py", line 4, in <module>
    from flurryapp.serializers.user_serializer import UserSerializer
  File "/home/ubuntu/flurry/flurryapp/serializers/user_serializer.py", line 4, in <module>
    from flurryapp.models import DriverSerializer
ImportError: cannot import name DriverSerializer
[2016-04-15 10:35:20 +0000] [11972] [INFO] Handling signal: term
[2016-04-15 10:35:20 +0000] [11978] [INFO] Worker exiting (pid: 11978)
[2016-04-15 10:35:20 +0000] [11982] [INFO] Worker exiting (pid: 11982)
[2016-04-15 10:35:20 +0000] [11981] [INFO] Worker exiting (pid: 11981)
[2016-04-15 10:35:20 +0000] [11972] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-15 10:35:21 +0000] [11996] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f67126b2410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f67126b2140>
  pre_fork: <function pre_fork at 0x7f67126b22a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f6712727f50>
  pre_exec: <function pre_exec at 0x7f67126b29b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f67126b2578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f67126b70c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f67126b2b18>
  post_request: <function post_request at 0x7f67126b2c08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f67126b26e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f67126b2d70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f6712727de8>
  worker_abort: <function worker_abort at 0x7f67126b2848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f67126b2ed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-15 10:35:21 +0000] [11996] [INFO] Starting gunicorn 19.4.5
[2016-04-15 10:35:21 +0000] [11996] [DEBUG] Arbiter booted
[2016-04-15 10:35:21 +0000] [11996] [INFO] Listening at: http://0.0.0.0:8001 (11996)
[2016-04-15 10:35:21 +0000] [11996] [INFO] Using worker: sync
[2016-04-15 10:35:21 +0000] [12002] [INFO] Booting worker with pid: 12002
[2016-04-15 10:35:21 +0000] [12003] [INFO] Booting worker with pid: 12003
[2016-04-15 10:35:21 +0000] [12008] [INFO] Booting worker with pid: 12008
[2016-04-15 10:35:21 +0000] [11996] [DEBUG] 3 workers
[2016-04-15 10:35:23 +0000] [12003] [DEBUG] GET /api/v1/flurry/users/
Internal Server Error: /api/v1/flurry/users/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 48, in list
    return Response(serializer.data)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 674, in data
    ret = super(ListSerializer, self).data
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 239, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 614, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 472, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/relations.py", line 220, in to_representation
    return value.pk
AttributeError: 'RelatedManager' object has no attribute 'pk'
[2016-04-15 10:40:42 +0000] [11996] [INFO] Handling signal: term
[2016-04-15 10:40:42 +0000] [12008] [INFO] Worker exiting (pid: 12008)
[2016-04-15 10:40:42 +0000] [12002] [INFO] Worker exiting (pid: 12002)
[2016-04-15 10:40:42 +0000] [12003] [INFO] Worker exiting (pid: 12003)
[2016-04-15 10:40:42 +0000] [11996] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-15 10:40:43 +0000] [12028] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f11915e1410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f11915e1140>
  pre_fork: <function pre_fork at 0x7f11915e12a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f1191656f50>
  pre_exec: <function pre_exec at 0x7f11915e19b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f11915e1578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f11915e60c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f11915e1b18>
  post_request: <function post_request at 0x7f11915e1c08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f11915e16e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f11915e1d70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f1191656de8>
  worker_abort: <function worker_abort at 0x7f11915e1848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f11915e1ed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-15 10:40:43 +0000] [12028] [INFO] Starting gunicorn 19.4.5
[2016-04-15 10:40:43 +0000] [12028] [DEBUG] Arbiter booted
[2016-04-15 10:40:43 +0000] [12028] [INFO] Listening at: http://0.0.0.0:8001 (12028)
[2016-04-15 10:40:43 +0000] [12028] [INFO] Using worker: sync
[2016-04-15 10:40:43 +0000] [12034] [INFO] Booting worker with pid: 12034
[2016-04-15 10:40:44 +0000] [12037] [INFO] Booting worker with pid: 12037
[2016-04-15 10:40:44 +0000] [12038] [INFO] Booting worker with pid: 12038
[2016-04-15 10:40:44 +0000] [12028] [DEBUG] 3 workers
[2016-04-15 10:40:48 +0000] [12037] [DEBUG] GET /api/v1/flurry/users/
[2016-04-15 10:41:23 +0000] [12038] [DEBUG] GET /api/v1/flurry/
[2016-04-15 10:41:26 +0000] [12037] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-15 10:41:34 +0000] [12038] [DEBUG] POST /api/v1/flurry/drivers/
[2016-04-15 10:41:40 +0000] [12034] [DEBUG] POST /api/v1/flurry/drivers/
[2016-04-15 10:41:46 +0000] [12038] [DEBUG] POST /api/v1/flurry/drivers/
[2016-04-15 10:41:47 +0000] [12037] [DEBUG] GET /api/v1/flurry/
[2016-04-15 10:41:50 +0000] [12038] [DEBUG] GET /api/v1/flurry/users/
[2016-04-15 10:42:01 +0000] [12037] [DEBUG] POST /api/v1/flurry/users/
[2016-04-15 10:42:27 +0000] [12038] [DEBUG] GET /api/v1/flurry/
[2016-04-15 10:42:28 +0000] [12034] [DEBUG] GET /api/v1/flurry/users/
[2016-04-15 10:47:07 +0000] [12037] [DEBUG] GET /api/v1/flurry/
[2016-04-15 10:47:10 +0000] [12034] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-15 10:47:58 +0000] [12037] [DEBUG] GET /api/v1/flurry/
[2016-04-15 10:48:00 +0000] [12038] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-15 10:50:43 +0000] [12028] [INFO] Handling signal: term
[2016-04-15 10:50:43 +0000] [12034] [INFO] Worker exiting (pid: 12034)
[2016-04-15 10:50:43 +0000] [12037] [INFO] Worker exiting (pid: 12037)
[2016-04-15 10:50:43 +0000] [12038] [INFO] Worker exiting (pid: 12038)
[2016-04-15 10:50:43 +0000] [12028] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-15 10:50:44 +0000] [12137] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f1c62f0c410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f1c62f0c140>
  pre_fork: <function pre_fork at 0x7f1c62f0c2a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f1c62f81f50>
  pre_exec: <function pre_exec at 0x7f1c62f0c9b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f1c62f0c578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f1c62f110c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f1c62f0cb18>
  post_request: <function post_request at 0x7f1c62f0cc08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f1c62f0c6e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f1c62f0cd70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f1c62f81de8>
  worker_abort: <function worker_abort at 0x7f1c62f0c848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f1c62f0ced8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-15 10:50:44 +0000] [12137] [INFO] Starting gunicorn 19.4.5
[2016-04-15 10:50:44 +0000] [12137] [DEBUG] Arbiter booted
[2016-04-15 10:50:44 +0000] [12137] [INFO] Listening at: http://0.0.0.0:8001 (12137)
[2016-04-15 10:50:44 +0000] [12137] [INFO] Using worker: sync
[2016-04-15 10:50:44 +0000] [12143] [INFO] Booting worker with pid: 12143
[2016-04-15 10:50:44 +0000] [12144] [INFO] Booting worker with pid: 12144
[2016-04-15 10:50:44 +0000] [12149] [INFO] Booting worker with pid: 12149
[2016-04-15 10:50:44 +0000] [12137] [DEBUG] 3 workers
[2016-04-15 10:50:48 +0000] [12144] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-15 10:51:50 +0000] [12137] [INFO] Handling signal: term
[2016-04-15 10:51:50 +0000] [12144] [INFO] Worker exiting (pid: 12144)
[2016-04-15 10:51:50 +0000] [12149] [INFO] Worker exiting (pid: 12149)
[2016-04-15 10:51:50 +0000] [12143] [INFO] Worker exiting (pid: 12143)
[2016-04-15 10:51:50 +0000] [12137] [INFO] Shutting down: Master
Starting flurry as ubuntu
[2016-04-15 10:51:51 +0000] [12160] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f53243ab410>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f53243ab140>
  pre_fork: <function pre_fork at 0x7f53243ab2a8>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: flurry
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f5324420f50>
  pre_exec: <function pre_exec at 0x7f53243ab9b0>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f53243ab578>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f53243b00c8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f53243abb18>
  post_request: <function post_request at 0x7f53243abc08>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f53243ab6e0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f53243abd70>
  chdir: /home/ubuntu/flurry
  paste: None
  default_proc_name: flurry.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f5324420de8>
  worker_abort: <function worker_abort at 0x7f53243ab848>
  bind: ['0.0.0.0:8001']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f53243abed8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-04-15 10:51:51 +0000] [12160] [INFO] Starting gunicorn 19.4.5
[2016-04-15 10:51:51 +0000] [12160] [DEBUG] Arbiter booted
[2016-04-15 10:51:51 +0000] [12160] [INFO] Listening at: http://0.0.0.0:8001 (12160)
[2016-04-15 10:51:51 +0000] [12160] [INFO] Using worker: sync
[2016-04-15 10:51:51 +0000] [12166] [INFO] Booting worker with pid: 12166
[2016-04-15 10:51:51 +0000] [12167] [INFO] Booting worker with pid: 12167
[2016-04-15 10:51:51 +0000] [12170] [INFO] Booting worker with pid: 12170
[2016-04-15 10:51:51 +0000] [12160] [DEBUG] 3 workers
[2016-04-15 10:51:53 +0000] [12167] [DEBUG] GET /api/v1/flurry/drivers/
[2016-04-15 10:52:29 +0000] [12170] [DEBUG] GET /api/v1/flurry/
[2016-04-15 10:52:38 +0000] [12167] [DEBUG] GET /api/v1/flurry/drivers/
